### ISSUE TITLE
Difficulty is not set correctly at the start of a game

### ISSUE THREAD

**Issue by baztheallmighty** [GenZmeY/KF2-StartWave#2]
Hi GenZmeY,
Cheers for fixing this mod up.

I have discovered a problem. The difficulty is not set correctly at the beginning of a game. This means it's no good for dedicated server use. If you use the setwave command however it sets the difficult correctly, however this requires admin interaction. 

How to recreate the problem. Use the settings like below and join the match and it's basically the same difficulty as wave 1. 

Relent settings:
` KFServer.exe KF-Spillway?Game=KFGameContent.KFGameInfo_Endless?Mutator=StartWave.StartWave?Difficulty=3`

```ini
[StartWave.StartWave]
;=Any settings not specified in the launch command will use the values stored here. If you use the same
;=settings often, it is recommended to store those here and only change what you need in the launch command.
;=
;=Whether mod-specific events should be logged.
bUseDebug=true
;=Whether an 'initial' trader time should occur before the first wave.
bStartWithTrader=true
;=The wave that the match should start on. It is clamped between wave 1 and the boss wave.
StartWave=50
;=The duration of the 'initial' trader (before the first wave).
InitialTraderTime=120
;=The duration of standard trader (between waves).
TraderTime=60
;=The starting dosh of players.
Dosh=25000
;=The boss override index. For the default boss list, 0-Hans, 1-Patty, 2-King FP, 3-Abomination. Negative
;=values can be used to keep the boss spawn random.
Boss=-1```

**Comment by GenZmeY** [comment]
Hey

Thx for describing how to reproduce the bug, I'll check it out

**Comment by baztheallmighty** [comment]
So I have done a little bit of looking. I added some logging statements as per below. The Difficulty is never updated unless the mutate command is called from the command line. After further investigation UpdateEndlessDifficulty is only called by SetWave and SetWave is only called by Mutate. 

```unrealscript
function UpdateEndlessDifficulty()
{
    local KFGameInfo_Endless Endless;
    local int i;
    
    Endless = KFGameInfo_Endless(MyKFGI);
    
    if(Endless == None)
    {
        return;
    }
    `log("SetWave: Start UpdateEndlessDifficulty.", true, 'StartWave');
    //Reflects the difficulty update in KFGameInfo_Endless.SetWave.
    Endless.bIsInHoePlus = false;
    Endless.ResetDifficulty();
    Endless.SpawnManager.GetWaveSettings(Endless.SpawnManager.WaveSettings);
    Endless.UpdateGameSettings();
    
    //Don't bother iterating for i=0-4, no difficulty increment can occur.
    for(i = 5; i < Endless.WaveNum; ++i)
    {
        //Simulate the death of a boss. The difficulty is incremented after each boss round.
        if(i % 5 == 0)
        {
            Endless.IncrementDifficulty();
            `log("SetWave: IncrementDifficulty.", true, 'StartWave');
        }
        
        //This should happen at the end of each wave (if we're in HoE+). The check is handled internally.
        //We do this after the simulation of a boss death so that bIsInHoePlus can be set first.
        Endless.HellOnEarthPlusRoundIncrement();
        `log("SetWave: HellOnEarthPlusRoundIncrement.", true, 'StartWave');
    }
}
```

I think the solution is to add UpdateEndlessDifficulty into StartWaveTimer. What do you think?
```unrealscript
function StartWaveTimer()
{
	local KFGameInfo_Survival KFGI_Surv;
	local PlayerController PC;
 
        ...

	KFGI_Surv.WaveNum = StartWave - 1;
	
	`log("WaveNum set to: "$KFGI_Surv.WaveNum, bUseDebug, 'StartWave');
	UpdateEndlessDifficulty();
```

**Comment by GenZmeY** [comment]
I'm sorry, but I haven't been able to find time for this yet. I remember this problem

**Comment by GenZmeY** [comment]
It's been a hell of a long time, but I've done this and more. Update: https://github.com/GenZmeY/KF2-StartWave/pull/4  

I'm not going to merge this yet, I'll wait for the game update to come out. Then I'll update all the mods at once  

and thanks for your suggested code, it made it easier to fix this bug

**Comment by GenZmeY** [comment]
Fixed in https://github.com/GenZmeY/KF2-StartWave/pull/4
